version: "3.9"
services:
  browser_crawler:
    build: browser-crawler
    restart: on-failure
    networks:
      - public
    ports:
      - "8010:8010"
  

networks:
  public:
    name: public
    external: true