version: "3.9"
services:
  myhome_bot:
    build: myhome_appartment_parser
    environment:
      BOT_TOKEN: 5844427862:AAG0TwhGifTxt-vNrXCs8cK6YsbMu2vQ_1M
    networks:
      - public


networks:
  public:
    name: public
    external: true